server:
  port: 8088
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: book-cloudnative-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/alerodrigues/book-cloudnative-config/config
          default-label: main	
